version: '3.3'


services:
  web:
    build: 
      ./web
    ports:      
      - '8080:80'
    volumes:       
      - './web:/app'
  redis:
    image: redis
    ports: 
      - "6379:6379"
    volumes: 
      - "./data:/data"
    command: redis-server --appendonly yes
